# Generated by Django 4.1.3 on 2022-11-17 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("content", models.TextField(max_length=280)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
